#!/usr/bin/env python3
# DH2Work: turn the assembled t32_armv8_seq.o into a C++ include file.
# Usage: gen_seq_inc.py <t32_armv8_seq.bin> <t32_armv8_seq.dis> <out.inc>
import re
import sys


def main():
    bin_path, dis_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(bin_path, "rb") as f:
        blob = f.read()

    pattern = re.compile(r"^\s*([0-9a-f]+):\s+([0-9a-f]{4})\s+([0-9a-f]{4})\s+([A-Za-z0-9_.]+)")
    entries = []
    with open(dis_path, "r", encoding="utf-8") as f:
        for line in f:
            match = pattern.match(line)
            if not match:
                continue
            offset = int(match.group(1), 16)
            name = match.group(4).lower()
            entries.append((name, offset, 4))

    if not entries:
        raise SystemExit("gen_seq_inc.py: no instructions parsed from " + dis_path)
    for name, offset, size in entries:
        if offset + size > len(blob):
            raise SystemExit("gen_seq_inc.py: %s runs past the %d-byte blob" % (name, len(blob)))

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Auto-generated by gen_seq_inc.py from t32_armv8_seq.s; do not edit.\n")
        f.write("#pragma once\n")
        f.write("static const unsigned char kSeqBlob[%d] = {\n" % len(blob))
        for i in range(0, len(blob), 12):
            f.write("    " + ", ".join("0x%02X" % b for b in blob[i:i + 12]) + ",\n")
        f.write("};\n")
        f.write("static const unsigned int kSeqBlobLen = %d;\n\n" % len(blob))
        f.write("struct T32SeqEntry { const char* name; unsigned int offset; unsigned int size; };\n")
        f.write("static const T32SeqEntry kSeqTable[] = {\n")
        for name, offset, size in entries:
            f.write('    {"%s", %d, %d},\n' % (name, offset, size))
        f.write("};\n")
        f.write("static const unsigned int kSeqCount = %d;\n" % len(entries))
    print("gen_seq_inc.py: %d entries, %d bytes -> %s" % (len(entries), len(blob), out_path))


if __name__ == "__main__":
    main()
